import Head from "next/head";
import Image from "next/image";
import { Tajawal } from "next/font/google";
import Link from "next/link";

const tajawal = Tajawal({
  weight: ["200", "300", "400", "500", "700", "800", "900"],
  subsets: ["arabic", "latin"],
});

export default function Home() {
  return (
    <>
      <Head>
        <title>The corporateor</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={tajawal.className}>
        الصفحة الرئيسية
        <div>
          <Link
            href="/survey"
            className="mt-8 ml-8 block w-28 rounded-md bg-cyan-800 px-6 py-3 text-white active:bg-cyan-600"
          >
            استبيان
          </Link>
        </div>
      </main>
    </>
  );
}
