import Head from "next/head";
import { Tajawal } from "next/font/google";
import Navbar from "@/components/Navbar";

const tajawal = Tajawal({
  weight: ["200", "300", "400", "500", "700", "800", "900"],
  subsets: ["arabic", "latin"],
});

export default function Home() {
  return (
    <>
      <Head>
        <title>The corporator</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta httpEquiv="X-UA-Compatible" content="ie=edge" />
        {/* ------------- FOR LATER ----------------------- */}
        {/* <meta name="description" content="" /> */}
        {/* <meta name="keywords" content="" /> */}
        <link rel="manifest" href="/manifest.json" />
        <link rel="apple-touch-icon" href="/apple-touch-icon.png" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={tajawal.className}>
        <Navbar />
        <section className="hero relative overflow-y-hidden py-36">
          <div className="absolute inset-0 -z-10">
            <img
              data-src="/flowers.jpg"
              alt="background texture"
              className="lazyload h-full w-full object-cover object-top contrast-50 grayscale-[0.5]"
            />
          </div>
          <div className="container flex h-full flex-col items-center justify-center gap-y-10 text-center text-white">
            <h1 className="text-3xl font-bold lg:text-5xl">
              قيمنا نطمح لتحقيقها
            </h1>
            <span className="sm:w-1/2">
              الإحترافية والذكاء، وضوح المهمات وتطبيقها، استثمار التطوير في
              مجالاته الواسعة، ثم الثقة. قيم نطمح لتحقيقها وتمثيلها بأدائنا
              التفاعلي مع مختلف عملائنا.
            </span>
            <div className="flex w-full flex-col gap-4 sm:flex-row sm:justify-center">
              <button className="btn sm:w-60">اطلب الان</button>
              <button className="outline-btn">تواصل معنا</button>
            </div>
          </div>
        </section>
        <section>
          <div className="container">
            <h2 className="text-3xl font-bold text-gray-900 lg:text-5xl">
              خدماتُنا
            </h2>
            <span>
              نمتلك خبرة طويلة في مجالنا، ولذلك نستطيع تقديم خدمات متميّزة لك.
            </span>
          </div>
        </section>
      </main>
    </>
  );
}
